/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ImageCard: typeof import('./src/components/card/ImageCard01.vue')['default']
    ImageCard01: typeof import('./src/components/card/ImageCard01.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepLoading: typeof import('./src/components/loading/StepLoading.vue')['default']
  }
}
